### ISSUE TITLE
Unreadable font colours

### ISSUE THREAD

**Issue by Jabokoe** [akalenuk/wordsandbuttons#13]
The inline stylesheet sets background-color for certain elements but not the color for the text overlaid on them leading to poor contrast and other unreadability.

**Comment by akalenuk** [comment]
Thanks! 
Indeed, the background may not work well with user settings for the font color. I didn't thing of that at all. Do you have specific examples in mind or is it just endemic?

**Comment by akalenuk** [comment]
I've just paired all the background-color with color: #000. This should help.
Thanks again!
