### ISSUE TITLE
Don't block Tor

### ISSUE THREAD

**Issue by Jookia** [akalenuk/wordsandbuttons#14]
Going to https://wordsandbuttons.online/ using Tor gives me this error: "Access denied. Your IP address is blacklisted. If you feel this is in error please contact your hosting provider's abuse department." It would be good to whitelist Tor

**Comment by akalenuk** [comment]
Hi,
I don't have any IPs blacklisted. Maybe Bluehost does without me knowing. But this is not endemic to Tor itself. I've just tried, with my network configuration it works ok. Maybe some specific end-points are blacklisted. Can you please try again?

**Comment by Jookia** [comment]
On Sun, Dec 22, 2019 at 12:42:45PM -0800, Oleksandr Kaleniuk wrote:
> Hi,
> I don't have any IPs blacklisted. Maybe Bluehost does without me knowing. But this is not endemic to Tor itself. I've just tried, with my network configuration it works ok. Maybe some specific end-points are blacklisted. Can you please try again? 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/akalenuk/wordsandbuttons/issues/14#issuecomment-568301415

Same issue. I imagine they're just blocking it based on a list or
something. This isn't good for Tor, VPN or CG-NAT users. :(

**Comment by milahu** [comment]
works now, i just tried from 3 exit nodes

**Comment by akalenuk** [comment]
I still don't know what is the underlying issue here. I never configured anything that wound have hurt Tor access to begin with.

But still, good to know that is works. Thank you!
