### ISSUE TITLE
Question 4 on "So you think you know C"

### ISSUE THREAD

**Issue by fluffy-critter** [akalenuk/wordsandbuttons#20]
The explanation for why 4 is undefined is technically correct (it's undefined behavior therefore undefined results), but even with UB I can't think of any implementation where the value wouldn't be 1. Even if `int` is 16 bits and there's some particularly weird implementation detail of how overshifting is handled on the architecture, any 16-bit integer shifted right by 16 bits will be either 0 or -1, and in both cases those would make the final result 1. What am I missing? Does C's specification allow for an implementation to have a `NaN`-type integer value that compares to `NaN` with other integers?

**Comment by akalenuk** [comment]
Please don't take the whole thing too seriously. It's just a funny test with funny results.

There is no such thing as standard NaN integers though, and this is a problem in itself. All the range of an integer type is numbers so you have to employ additional mechanisms to register overflows or shift errors. Those are not covered by the C standard at all (although I'm not familiar with C23 to be honest).

**Comment by fluffy-critter** [comment]
Yeah, I'm not taking it seriously and I also agree that "don't know" is the correct answer.

I was mostly just wondering if you knew of a situation that the UB would actually manifest as a return value other than 1. The explanation given for why it's UB is that the overflow of the int16 is not specified, but there's still no possible bit pattern stored in the int16 that would result in a different result. I suppose there could be something especially zany that an optimizer does though.
