### ISSUE TITLE
replace <a/> with </a>

### ISSUE THREAD

**Issue by milahu** [akalenuk/wordsandbuttons#21]
this invalid html would be detected by a linter

```
$ tidy the_real_cpp_killers.html >/dev/null
line 113 column 200 - Warning: missing </a> before <a>
line 478 column 389 - Warning: missing </a> before <a>
```

https://github.com/akalenuk/wordsandbuttons/blob/2f0a8c50d83c8926a1d14e9315b017bf1809495f/pages/the_real_cpp_killers.html#L478

**Comment by akalenuk** [comment]
Thank you! Fixed.
Is tidy more powerful than Firefox view source feature? It does find HTML inconsistencies too.

**Comment by milahu** [comment]
tidy is just an example
personally, i use the node package [html-validate](https://www.npmjs.com/package/html-validate)

<details>
<summary>
html-validate
</summary>

with this `htmlvalidate.config.json`

```json
{
  "extends": ["html-validate:recommended"],
  "rules": {
    "attr-quotes": "off",
    "element-name": "off",
    "unrecognized-char-ref": "off",
    "no-inline-style": "off",
    "wcag/h37": "off",
    "void-style": "off",
    "prefer-tbody": "off",
    "doctype-style": "off",
    "svg-focusable": "off",
    "wcag/h67": "off",
    "element-permitted-content": "error",
    "text-content": "off",
    "prefer-native-element": "off",
    "element-permitted-content": "off",
    "attr-spacing": "off",
    "attr-case": "off",
    "close-attr": "off",
    "no-dup-attr": "off"
  }
}
```

and with this `validate-html.sh`

```sh
#! /bin/sh

set -e

cd "$(dirname "$0")"/..

html_files=(
  a.html
  b.html
)

exec ./node_modules/html-validate/bin/html-validate.js \
  --config=scripts/htmlvalidate.config.json \
  "${html_files[@]}"
```

</details>

---

btw, i found you via [reddit: The Real C++ Killers (Not You, Rust)](https://www.reddit.com/r/programming/comments/1c91a29/the_real_c_killers_not_you_rust/)

the [spiral](https://github.com/spiral-software/spiral-software) language looks really impressive...
at least to me as a member of [tribe performance](https://josephg.com/blog/3-tribes/#programmingashardwarehacking)

<blockquote>

> Why would anyone write in C++ if writing in high-level algorithm description language makes your code 2x faster?

its the curse of popularity:

- [spiral](https://github.com/spiral-software/spiral-software) has 100 github stars
- [nim](https://github.com/nim-lang/Nim) has 15K github stars
- [zig](https://github.com/ziglang/zig) has 30K github stars
- [carbon](https://github.com/carbon-language/carbon-lang) has 30K github stars
- [rust](https://github.com/rust-lang/rust) has 90K github stars

similar: react is slow but popular. (who the fuck decides what becomes popular?)

</blockquote>

**Comment by akalenuk** [comment]
Nice! I should try that html-validate. I've got lazy with editing lately, there are probably tons of small bugs everywhere.
Thanks!

I don't know who decides what becomes popular. Definitely not me :-) I often write to bring some exposure to unpopular but impressive things, but it's like pushing a barge. Not a one man job.
